n1=input("Enter a Number:")
n2=input("Enter a Number:")
n3=input("Enter a Number:")
n4=input("Enter a Number:")
n5=input("Enter a Number:")
n1=int(n1) 
n2=int(n2)
n3=int(n3)
n4=int(n4)
n5=int(n5)
print("總和："+str(n1+n2+n3+n4+n5))
print("最大值："+str(max([n1,n2,n3,n4,n5])))